version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npm test && echo "Hi from Docs"
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run: echo "Empty Test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test