 version: 2
 jobs:
   docs:
     docker:
       - image: circleci/ruby:2.4.1
     # Steps are a list of commands to run inside the docker container above.
     steps:
       - checkout
       - run: echo "Hello from Discovery Docs"
       - run: sleep 5

 workflows:
   version: 2
   docs_jobs: # this is the name of our workflow
     jobs:
       - docs
