# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# TODO: Get rid of all this CircleCI caching in favor of extended Docker images
#
version: 2
jobs:
  ut-components:
    docker:
      - image: python:3.6-slim-stretch
        environment:
          LANG: C.UTF-8
          PYTHONUNBUFFERED: 1

      - image: postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
          POSTGRES_DB: circle-test

    working_directory: /var/local

    steps:
      - run:
          name: Install development tools
          command: |
            apt-get update
            apt-get install -y git gcc

      - checkout

      - run:
          name: Set CircleCI configuration
          command: |
            cp ./app/discovery/local_settings.circle.py ./app/discovery/local_settings.py

      - run:
          name: Install requirements
          command: |
            pip install --no-cache-dir -r ./requirements.txt
            pip install --no-cache-dir -r ./requirements-dev.txt
            ./scripts/init-webserver.sh /dev/stderr

      - run:
          name: Run component tests
          no_output_timeout: 1h
          command: |
            ./run test --parallel=4 discovery categories vendors contracts

      - store_artifacts:
          path: logs
          destination: component-test-reports

  ut-core-api:
    docker:
      - image: python:3.6-slim-stretch
        environment:
          LANG: C.UTF-8
          PYTHONUNBUFFERED: 1

      - image: postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
          POSTGRES_DB: circle-test

    working_directory: /var/local

    steps:
      - run:
          name: Install development tools
          command: |
            apt-get update
            apt-get install -y git gcc

      - checkout

      - run:
          name: Set CircleCI configuration
          command: |
            cp ./app/discovery/local_settings.circle.py ./app/discovery/local_settings.py

      - run:
          name: Install requirements
          command: |
            pip install --no-cache-dir -r ./requirements.txt
            pip install --no-cache-dir -r ./requirements-dev.txt
            ./scripts/init-webserver.sh /dev/stderr

      - run:
          name: Run core API tests
          no_output_timeout: 1h
          command: |
            ./run test api --tag=object
            ./run test api --tag=ordering
            ./run test api --tag=pagination
            ./run test api --tag=search
            ./run test api --tag=request
            ./run test api --tag=info

      - store_artifacts:
          path: logs
          destination: core-api-test-reports

  ut-api-fields:
    docker:
      - image: python:3.6-slim-stretch
        environment:
          LANG: C.UTF-8
          PYTHONUNBUFFERED: 1

      - image: postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
          POSTGRES_DB: circle-test

    working_directory: /var/local

    steps:
      - run:
          name: Install development tools
          command: |
            apt-get update
            apt-get install -y git gcc

      - checkout

      - run:
          name: Set CircleCI configuration
          command: |
            cp ./app/discovery/local_settings.circle.py ./app/discovery/local_settings.py

      - run:
          name: Install requirements
          command: |
            pip install --no-cache-dir -r ./requirements.txt
            pip install --no-cache-dir -r ./requirements-dev.txt
            ./scripts/init-webserver.sh /dev/stderr

      - run:
          name: Run API field tests
          no_output_timeout: 1h
          command: |
            ./run test api --tag=field_test

      - store_artifacts:
          path: logs
          destination: api-field-test-reports

  ut-api-values:
    docker:
      - image: python:3.6-slim-stretch
        environment:
          LANG: C.UTF-8
          PYTHONUNBUFFERED: 1

      - image: postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
          POSTGRES_DB: circle-test

    working_directory: /var/local

    steps:
      - run:
          name: Install development tools
          command: |
            apt-get update
            apt-get install -y git gcc

      - checkout

      - run:
          name: Set CircleCI configuration
          command: |
            cp ./app/discovery/local_settings.circle.py ./app/discovery/local_settings.py

      - run:
          name: Install requirements
          command: |
            pip install --no-cache-dir -r ./requirements.txt
            pip install --no-cache-dir -r ./requirements-dev.txt
            ./scripts/init-webserver.sh /dev/stderr

      - run:
          name: Run API values tests
          no_output_timeout: 1h
          command: |
            ./run test api --tag=values_test

      - store_artifacts:
          path: logs
          destination: api-values-test-reports

  at-all:
    docker:
      - image: python:3.6-slim-stretch
        environment:
          LANG: C.UTF-8
          PYTHONUNBUFFERED: 1

      - image: postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
          POSTGRES_DB: circle-test

    working_directory: /var/local

    steps:
      - run:
          name: Install development tools
          command: |
            apt-get update
            apt-get install -y git gcc

      - checkout

      - run:
          name: Set CircleCI configuration
          command: |
            cp ./app/discovery/local_settings.circle.py ./app/discovery/local_settings.py

      - run:
          name: Install requirements
          command: |
            pip install --no-cache-dir -r ./requirements.txt
            pip install --no-cache-dir -r ./requirements-dev.txt

      - run:
          name: Install Chrome web driver
          command: |
            ./scripts/setup-chrome.sh /dev/stderr

      - run:
          background: true
          command: Xvfb -ac :99 -screen 0 1280x1024x16 +extension RANDR > /dev/null 2>&1

      - run:
          name: Import fixtures and run test server
          background: true
          command: |
            ./scripts/init-db.sh /dev/stderr
            ./scripts/init-webserver.sh /dev/stderr
            ./scripts/load-fixtures.sh
            cd app
            waitress-serve --expose-tracebacks --port=8080 discovery.wsgi:application

  dep-dev:
    docker:
      - image: debian:stretch-slim
        environment:
          CF_LOGIN_URL: 'https://api.fr.cloud.gov'

    working_directory: /var/local

    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install -y git

      - checkout

      - run:
          name: Setup CloudFoundry client CLI
          command: |
            ./scripts/setup-cf.sh /dev/stderr

      - run:
          name: Deploy development applications
          command: |
            ./scripts/deploy-dev.sh

      - store_artifacts:
          <<: *logging
          destination: dev-deploy-reports

  dep-stage:
    docker:
      - image: debian:stretch-slim
        environment:
          CF_LOGIN_URL: 'https://api.fr.cloud.gov'

    working_directory: /var/local

    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install -y git

      - checkout

      - run:
          name: Setup CloudFoundry client CLI
          command: |
            ./scripts/setup-cf.sh /dev/stderr

      - run:
          name: Deploy development applications
          command: |
            ./scripts/deploy-staging.sh
            
  dep-prod:
    docker:
      - image: debian:stretch-slim
        environment:
          CF_LOGIN_URL: 'https://api.fr.cloud.gov'

    working_directory: /var/local

    steps:
      - run:
          name: Install Git
          command: |
            apt-get update
            apt-get install -y git

      - checkout

      - run:
          name: Setup CloudFoundry client CLI
          command: |
            ./scripts/setup-cf.sh /dev/stderr

      - run:
          name: Deploy production applications
          command: |
            ./scripts/deploy-prod.sh

  dep-docs:
    docker:
      - image: python:3.6-slim-stretch
        environment:
          LANG: C.UTF-8
          PYTHONUNBUFFERED: 1

    working_directory: /var/local

    steps:
      - run:
          name: Install development tools
          command: |
            apt-get update
            apt-get install -y git gcc make

      - checkout

      - run:
          name: Install requirements
          command: |
            pip install --no-cache-dir -r ./requirements.txt
            pip install --no-cache-dir -r ./requirements-dev.txt

      - run:
          name: Deploy documentation
          command: |
            git config --global user.name "CircleCI ( ${CIRCLE_USERNAME} )"
            git config --global user.email "${CIRCLE_USERNAME}@${CIRCLE_BRANCH}"
            ./scripts/deploy-docs.sh "${CIRCLE_BRANCH}"

      - store_artifacts:
          path: logs
          destination: docs-reports

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - ut-components
      - ut-core-api
      - ut-api-fields
      - ut-api-values
      - at-all
      - dep-dev:
          requires:
            - ut-components
            - ut-core-api
            - ut-api-fields
            - ut-api-values
            - at-all
          filters:
            branches:
              only: develop
      - dep-prod:
          requires:
            - ut-components
            - ut-core-api
            - ut-api-fields
            - ut-api-values
            - at-all
          filters:
            branches:
              only: master
      - dep-docs:
          requires:
            - ut-components
          filters:
            branches:
              only:
                - master
                - docs
      - dep-stage:
          requires:
            - ut-components
            - ut-core-api
            - ut-api-fields
            - ut-api-values
            - at-all
          filters:
            branches:
              only:
                - staging