version: '2.3'
services:
  lb:
    image: eeacms/haproxy
    restart: always
    environment:
      FRONTEND_PORT: 5000
      BACKENDS: "web"
      BALANCE: "roundrobin"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"

  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: discovery
      POSTGRES_PASSWORD: discovery
      POSTGRES_DB: discovery

  queue:
    image: redis:3.2
    restart: always
    command: redis-server --requirepass discovery

  django:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - django-env.vars
    volumes:
      - ..:/discovery
    environment:
      # What CloudFoundry gives us...
      DATABASE_URL: postgres://discovery:discovery@discovery-db:5432/discovery
      VCAP_SERVICES: >-
        {
          "aws-rds": [
            {
              "credentials": {
                "uri": "postgres://discovery:discovery@discovery-db:5432/discovery",
                "host": "discovery-db",
                "port": "5432",
                "username": "discovery",
                "password": "discovery",
                "db_name": "discovery"
              },
              "label": "aws-rds",
              "name": "discovery-db",
              "tags": [
                "database",
                "RDS",
                "postgresql"
              ]
            }
          ],
          "redis32": [
            {
              "credentials": {
                "uri": "redis://:discovery@discovery-tasks:6379",
                "hostname": "discovery-tasks",
                "port": "6379",
                "password": "discovery"
              },
              "label": "redis32",
              "name": "discovery-tasks",
              "tags": [
                "redis32",
                "redis"
              ]
            }
          ]
        }
